# fly.toml app configuration file generated for dataroc-api on 2023-06-21T19:15:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dataroc-api"
primary_region = "yul"

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
